version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=spending-frustration
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:ro
      - ./frontend:/frontend:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  mongo-data:
